### ISSUE TITLE
How it work ?

### ISSUE THREAD

**Issue by spham** [HendrikPrinsZA/laravel-kata#160]
I think something is incompleted

**Comment by HendrikPrinsZA** [comment]
@spham, it needs a bit of attention to work out the sequence for developers. But you should be able to get it going with the standard Laravel sequence like for [sail](https://laravel.com/docs/10.x/sail#main-content).
```sh
composer install
./vendor/bin/sail up -d
./vendor/bin/sail artisan migrate --seed
```

Then try to run it with 
```sh
./vendor/bin/sail artisan kata:run
```

You can read about the idea behind it in [this blog post](https://medium.com/p/acf74404654b).
